version: "3.9"
services:
  3dtiles.app:
    image: test-cesium-3dtiles:cesium
    ports:
      - "8080:8080"
    networks:
      - 3dtiles-net
    depends_on:
      - 3dtiles.data
  3dtiles.data:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/3DBAG/out_tmp/glb:/3dtiles
    ports:
      - "8003:80"
    networks:
      - 3dtiles-net

networks:
  3dtiles-net: {}