version: "3.8"
services:
  3dtiles.app:
    image: test-cesium-3dtiles:cesium
    build:
      context: .
      dockerfile: cesium.dockerfile
    ports:
      - "8080:8080"
    networks:
      - 3dtiles-net
    depends_on:
      - 3dtiles-buildings.data
      - 3dtiles-terrrain.data
  3dtiles-terrrain.data:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /dev/shm/3dtiles-terrain:/3dtiles
    ports:
      - "8004:80"
    networks:
      - 3dtiles-net
  3dtiles-buildings.data:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /data/3DBAG/out_tmp/docker:/3dtiles
#      - /data/3DBAG/out_tmp/glb:/3dtiles
      - /data/work/bdukai/3dbasisvoorziening/3dtiles_buildings:/3dtiles
#      - /dev/shm/3dtiles-buildings:/3dtiles
    ports:
      - "8003:80"
    networks:
      - 3dtiles-net

networks:
  3dtiles-net: {}